name: NATS-S3 Code Coverage

on:
  workflow_dispatch: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Go fmt check
        run: |
          files=$(gofmt -s -l .)
          if [ -n "$files" ]; then
            echo "Unformatted files:" && echo "$files" && exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Test with coverage
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Coverage summary
        run: go tool cover -func=coverage.out | tail -n 1

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

