name: Coverage

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to run against'
        required: true
        default: 'main'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-coverage:
    name: Unit test coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run coverage
        run: |
          make coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          flags: unit
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

